// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtePNROwwmzftNyf6RTkzQi-llHAVPX_E',
    appId: '1:174885866179:web:d6f3794390c2deb3813076',
    messagingSenderId: '174885866179',
    projectId: 'final-8dda1',
    authDomain: 'final-8dda1.firebaseapp.com',
    storageBucket: 'final-8dda1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgx9FFPa7JSBLszWejOGQNO18gFMzUwps',
    appId: '1:174885866179:android:dbef835f478e4f7d813076',
    messagingSenderId: '174885866179',
    projectId: 'final-8dda1',
    storageBucket: 'final-8dda1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkXeuM--uaMNPbJYvjAQpHLexurG7B8AE',
    appId: '1:174885866179:ios:1a4bdc6ce0e17bd8813076',
    messagingSenderId: '174885866179',
    projectId: 'final-8dda1',
    storageBucket: 'final-8dda1.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkXeuM--uaMNPbJYvjAQpHLexurG7B8AE',
    appId: '1:174885866179:ios:1a4bdc6ce0e17bd8813076',
    messagingSenderId: '174885866179',
    projectId: 'final-8dda1',
    storageBucket: 'final-8dda1.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtePNROwwmzftNyf6RTkzQi-llHAVPX_E',
    appId: '1:174885866179:web:36b998ed7f65a370813076',
    messagingSenderId: '174885866179',
    projectId: 'final-8dda1',
    authDomain: 'final-8dda1.firebaseapp.com',
    storageBucket: 'final-8dda1.appspot.com',
  );

}